diff --git a/Makefile b/Makefile
index 896ff8b..417f138 100644
--- a/Makefile
+++ b/Makefile
@@ -24,15 +24,13 @@ all-libs:
 
 .PHONY: install
 install:
-	for kind in $(ALL_LIBRARY_TYPES) ; do \
 		gprinstall -P adasat.gpr -p -f \
-			-XLIBRARY_TYPE=$$kind \
+			-XLIBRARY_TYPE=$(LIBRARY_TYPE) \
 			-XBUILD_MODE=$(BUILD_MODE) \
 			--relocate-build-tree="$(BUILD_DIR)" \
 			--prefix="$(INSTALL_DIR)" \
-			--build-name=$$kind \
+			--build-name=$(LIBRARY_TYPE) \
 			--build-var=LIBRARY_TYPE ; \
-	done
 
 .PHONY: test
 clean:
